// Mapeo nombre de equipo (backend) → código ISO 3166-1 alpha-2
// Versión consolidada y deduplicada de todos los archivos del proyecto
export const NAME_TO_ISO2 = {
  // CONCACAF
  'méxico': 'MX', 'mexico': 'MX',
  'canadá': 'CA', 'canada': 'CA',
  'estados unidos': 'US', 'usa': 'US', 'united states': 'US',
  'costa rica': 'CR',
  'panamá': 'PA', 'panama': 'PA',
  'honduras': 'HN',
  'jamaica': 'JM',
  'el salvador': 'SV',
  'trinidad y tobago': 'TT', 'trinidad and tobago': 'TT', 'trinidad & tobago': 'TT',
  'haiti': 'HT', 'haití': 'HT',
  'cuba': 'CU',
  'guatemala': 'GT',
  'nicaragua': 'NI',
  'curaçao': 'CW', 'curacao': 'CW',

  // CONMEBOL
  'argentina': 'AR',
  'brasil': 'BR', 'brazil': 'BR',
  'uruguay': 'UY',
  'colombia': 'CO',
  'perú': 'PE', 'peru': 'PE',
  'chile': 'CL',
  'venezuela': 'VE',
  'paraguay': 'PY',
  'bolivia': 'BO',
  'ecuador': 'EC',

  // UEFA
  'francia': 'FR', 'france': 'FR',
  'españa': 'ES', 'espana': 'ES', 'spain': 'ES',
  'alemania': 'DE', 'germany': 'DE',
  'portugal': 'PT',
  'inglaterra': 'GB', 'england': 'GB',
  'países bajos': 'NL', 'paises bajos': 'NL', 'holanda': 'NL', 'netherlands': 'NL', 'holland': 'NL',
  'croacia': 'HR', 'croatia': 'HR',
  'bélgica': 'BE', 'belgica': 'BE', 'belgium': 'BE',
  'polonia': 'PL', 'poland': 'PL',
  'dinamarca': 'DK', 'denmark': 'DK',
  'suiza': 'CH', 'switzerland': 'CH',
  'serbia': 'RS',
  'austria': 'AT',
  'suecia': 'SE', 'sweden': 'SE',
  'noruega': 'NO', 'norway': 'NO',
  'finlandia': 'FI', 'finland': 'FI',
  'islandia': 'IS', 'iceland': 'IS',
  'escocia': 'GB', 'scotland': 'GB',
  'gales': 'GB', 'wales': 'GB',
  'irlanda del norte': 'GB', 'northern ireland': 'GB',
  'irlanda': 'IE', 'ireland': 'IE', 'republic of ireland': 'IE',
  'turquía': 'TR', 'turquia': 'TR', 'turkey': 'TR', 'türkiye': 'TR',
  'grecia': 'GR', 'greece': 'GR',
  'ucrania': 'UA', 'ukraine': 'UA',
  'hungría': 'HU', 'hungria': 'HU', 'hungary': 'HU',
  'rumanía': 'RO', 'rumania': 'RO', 'romania': 'RO',
  'república checa': 'CZ', 'republica checa': 'CZ', 'czech republic': 'CZ', 'czechia': 'CZ',
  'eslovaquia': 'SK', 'slovakia': 'SK',
  'eslovenia': 'SI', 'slovenia': 'SI',
  'albania': 'AL',
  'macedonia del norte': 'MK', 'north macedonia': 'MK',
  'bosnia y herzegovina': 'BA', 'bosnia and herzegovina': 'BA', 'bosnia-herzegovina': 'BA', 'bosnia & herzegovina': 'BA',
  'montenegro': 'ME',
  'luxemburgo': 'LU', 'luxembourg': 'LU',
  'georgia': 'GE',
  'armenia': 'AM',
  'azerbaiyán': 'AZ', 'azerbaijan': 'AZ',
  'bielorrusia': 'BY', 'belarus': 'BY',
  'moldavia': 'MD', 'moldova': 'MD',
  'kosovo': 'XK',

  // CAF (África)
  'marruecos': 'MA', 'morocco': 'MA',
  'senegal': 'SN',
  'ghana': 'GH',
  'camerún': 'CM', 'camerun': 'CM', 'cameroon': 'CM',
  'túnez': 'TN', 'tunez': 'TN', 'tunisia': 'TN',
  'nigeria': 'NG',
  'egipto': 'EG', 'egypt': 'EG',
  'mali': 'ML',
  'costa de marfil': 'CI', 'costa de márfil': 'CI', 'ivory coast': 'CI', "côte d'ivoire": 'CI', "cote d'ivoire": 'CI', 'cote divoire': 'CI',
  'angola': 'AO',
  'mozambique': 'MZ',
  'zimbabue': 'ZW', 'zimbabwe': 'ZW',
  'zambia': 'ZM',
  'tanzania': 'TZ',
  'uganda': 'UG',
  'namibia': 'NA',
  'guinea': 'GN',
  'burkina faso': 'BF',
  'gambia': 'GM',
  'comoras': 'KM', 'comoros': 'KM',
  'cabo verde': 'CV', 'cape verde': 'CV', 'cape verde islands': 'CV',
  'libia': 'LY', 'libya': 'LY',
  'argelia': 'DZ', 'algeria': 'DZ',
  'sudáfrica': 'ZA', 'sudafrica': 'ZA', 'south africa': 'ZA',
  'etiopía': 'ET', 'etiopia': 'ET', 'ethiopia': 'ET',
  'kenia': 'KE', 'kenya': 'KE',
  'república democrática del congo': 'CD', 'dr congo': 'CD', 'congo dr': 'CD', 'rd congo': 'CD', 'democratic republic of congo': 'CD', 'rdc': 'CD',
  'guinea ecuatorial': 'GQ', 'equatorial guinea': 'GQ',
  'benín': 'BJ', 'benin': 'BJ',
  'sudán': 'SD', 'sudan': 'SD',
  'mauritania': 'MR',

  // AFC (Asia)
  'japón': 'JP', 'japon': 'JP', 'japan': 'JP',
  'corea del sur': 'KR', 'south korea': 'KR', 'korea republic': 'KR', 'republic of korea': 'KR',
  'corea del norte': 'KP', 'north korea': 'KP',
  'arabia saudita': 'SA', 'saudi arabia': 'SA',
  'irán': 'IR', 'iran': 'IR', 'ir iran': 'IR',
  'australia': 'AU',
  'china': 'CN',
  'qatar': 'QA',
  'emiratos árabes unidos': 'AE', 'emiratos arabes unidos': 'AE', 'united arab emirates': 'AE', 'uae': 'AE',
  'irak': 'IQ', 'iraq': 'IQ',
  'jordania': 'JO', 'jordan': 'JO',
  'omán': 'OM', 'oman': 'OM',
  'baréin': 'BH', 'bahrain': 'BH',
  'kuwait': 'KW',
  'siria': 'SY', 'syria': 'SY',
  'uzbekistán': 'UZ', 'uzbekistan': 'UZ',
  'kirguistán': 'KG', 'kyrgyzstan': 'KG',
  'tayikistán': 'TJ', 'tajikistan': 'TJ',
  'india': 'IN',
  'indonesia': 'ID',
  'filipinas': 'PH', 'philippines': 'PH',
  'tailandia': 'TH', 'thailand': 'TH',
  'vietnam': 'VN',
  'palestina': 'PS', 'palestine': 'PS',

  // OFC
  'nueva zelanda': 'NZ', 'new zealand': 'NZ',
};

export const teamIso2 = (name) => {
  if (!name) return null;
  return NAME_TO_ISO2[name.trim().toLowerCase()] || null;
};
